version: "3.8"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fastapi-prod
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    restart: always
    networks:
      - fastapi-network
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M

networks:
  fastapi-network:
    driver: bridge
